/**
 * The production adapter's billing pass-through (#126): with the `ai` SDK
 * mocked, ply's own PRODUCTION_UNIFORM_PROVIDER must carry the provider
 * response's own per-request billing into the seam type — the Gateway returns
 * it as `providerMetadata.gateway.cost` beside the generated bytes (observed
 * as a decimal string, e.g. "0.006255", in the #126 comparison receipts). A
 * response that reported no billing must carry no billing claim at all, and
 * unreadable billing metadata must not become a zero charge: the seam is the
 * one boundary where that external shape becomes a trusted amount, and no
 * separate lookup call is ever made. No network, no billing.
 */
import { describe, test, expect, mock, beforeEach, afterEach } from "bun:test";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";

/** The provider-metadata shape a billed Gateway response returned (observed, #126). */
const GATEWAY_RECEIPT = { gateway: { cost: "0.006255" } };

let imageProviderMetadata: unknown = GATEWAY_RECEIPT;
let textProviderMetadata: unknown = undefined;
const imageArgs: Record<string, unknown>[] = [];

mock.module("ai", () => ({
  generateImage: async (args: Record<string, unknown>) => {
    imageArgs.push(args);
    return {
      images: [{ base64: Buffer.from("adapter-cost").toString("base64") }],
      warnings: [],
      providerMetadata: imageProviderMetadata,
    };
  },
  generateText: async () => ({
    files: [{ mediaType: "image/png", uint8Array: Buffer.from("adapter-cost-text") }],
    text: "",
    warnings: [],
    providerMetadata: textProviderMetadata,
  }),
}));

let root: string;
let jobsRoot: string;

beforeEach(async () => {
  root = await mkdtemp(path.join(tmpdir(), "ply-cost-adapter-"));
  jobsRoot = path.join(root, "generation");
  imageArgs.length = 0;
  imageProviderMetadata = GATEWAY_RECEIPT;
  textProviderMetadata = undefined;
});

afterEach(async () => {
  await rm(root, { recursive: true, force: true });
});

describe("PRODUCTION_UNIFORM_PROVIDER — the response's own billing reaches the seam (#126)", () => {
  test("the Gateway's per-request cost is carried through as a billing receipt", async () => {
    // Imported lazily so the mock is definitely armed first.
    const { PRODUCTION_UNIFORM_PROVIDER } = await import("../src/generation-cli.js");
    const result = await PRODUCTION_UNIFORM_PROVIDER.image({
      model: "openai/gpt-image-2",
      prompt: "a barn at noon",
      size: "1024x1024",
    });
    expect(result.billing).toEqual({ costUsd: 0.006255 });
    // The receipt is read from the response; no second request is made.
    expect(imageArgs).toHaveLength(1);
  });

  test("a multimodal response's receipt is carried through too", async () => {
    textProviderMetadata = { gateway: { cost: 0.067036 } };
    const { PRODUCTION_UNIFORM_PROVIDER } = await import("../src/generation-cli.js");
    const result = await PRODUCTION_UNIFORM_PROVIDER.text({
      model: "google/gemini-3.1-flash-image",
      prompt: "a barn at noon",
    });
    expect(result.billing).toEqual({ costUsd: 0.067036 });
  });

  test("no billing claim is made when the response reported none or reported nonsense", async () => {
    const metadataCases: unknown[] = [
      undefined,
      {},
      { gateway: {} },
      { openai: { images: [{ size: "1024x1024" }] } },
      { gateway: { cost: null } },
      { gateway: { cost: "not-a-number" } },
      { gateway: { cost: "" } },
      { gateway: { cost: -0.01 } },
    ];
    const { PRODUCTION_UNIFORM_PROVIDER } = await import("../src/generation-cli.js");
    for (const metadata of metadataCases) {
      imageProviderMetadata = metadata;
      const result = await PRODUCTION_UNIFORM_PROVIDER.image({
        model: "openai/gpt-image-2",
        prompt: "a barn at noon",
      });
      expect(result.billing).toBeUndefined();
    }
  });

  test("a published run through the production adapter records the charge it was told", async () => {
    const { run } = await import("../src/generation-cli.js");
    const res = await run(["a barn at noon", "--model", "gpt-image", "--job", "gen-adapter-billed", "--json"], {
      jobsRoot,
    });
    expect(res.exitCode).toBe(0);
    const record = JSON.parse(await readFile(path.join(jobsRoot, "gen-adapter-billed", "job.json"), "utf8"));
    expect(record.schemaVersion).toBe(2);
    expect(record.run.cost).toEqual({ basis: "actual-charge", usd: 0.006255 });
  });
});
